apiVersion: v1
kind: Namespace
metadata:
  labels:
    control-plane: controller-manager
  name: system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: controller-manager
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  minReadySeconds: 120
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      annotations:
        kubectl.kubernetes.io/default-container: manager
      labels:
        control-plane: controller-manager
        app: metalnet
    spec:
      containers:
      - command:
        - /manager
        env:
        - name: NODE_NAME
          valueFrom:
            fieldRef:
              fieldPath: spec.nodeName
        - name: NODE_IP
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: status.hostIP
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        args:
        - --health-probe-bind-address=:8081
        - --node-name=$(NODE_NAME)
        - --pod-name=$(POD_NAME)
        - --dp-service-address=[$(NODE_IP)]:1337
        image: controller:latest
        name: manager
        ports: []
        resources:
          limits:
            cpu: 500m
            memory: 128Mi
          requests:
            cpu: 10m
            memory: 64Mi
        imagePullPolicy: IfNotPresent
        livenessProbe:
          httpGet:
            path: /healthz
            port: 8081
          failureThreshold: 1
          initialDelaySeconds: 10
          periodSeconds: 10
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /sys
          name: sysfs
        - mountPath: /usr/share/misc/
          name: pciids
        - mountPath: /var/lib/metalnet
          name: metalnet
      volumes:
      - hostPath:
          path: /sys
          type: ""
        name: sysfs
      - hostPath:
          path: /usr/share/misc/
          type: ""
        name: pciids
      - hostPath:
          path: /var/lib/metalnet
          type: DirectoryOrCreate
        name: metalnet
      serviceAccountName: controller-manager
      terminationGracePeriodSeconds: 10
